### ISSUE TITLE
Layout problem in latest sources

### ISSUE THREAD

**Issue by metaphore** [morevnaproject-org/papagayo-ng#19]
Hello guys,
I used stable release version of Papagayo-NG (the one that available under "release" section of this repo) and everything was fine. Than I noticed that this version is a bit outdated due to latest sources and I have downloaded sources from last commit 24aaaac3f82dd76732b8604e65c9d5d818241333, built it and got some weird picture (Win10):

![image](https://cloud.githubusercontent.com/assets/6159734/16548150/eb9cf5a8-41af-11e6-8912-c890c9480337.png)

It seems like layout broken and I can't fix it because I don't know Python. Can somebody check it and help me with this?

Thanks
##

**Comment by Metaphore** [comment]
Oh, I just have noticed that after window resize everything gets to normal.
But I think it's still worth to be fixed

**Comment by morevnaproject** [comment]
@metaphore Please check if the bug still exists with our latest release build - https://morevnaproject.org/2017/05/15/introducing-papagayo-ng/
