### ISSUE TITLE
Audio and Visual issues

### ISSUE THREAD

**Issue by Hippyjake** [morevnaproject-org/papagayo-ng#30]
Using the 1.4.1 Appimage I have some problems. I'm not quite sure how to explain it so here is a video.

https://youtu.be/eeYmYUiFhW8

**Comment by steveway** [comment]
Yeah, the WaveformView is a pretty messy widget.
I'm doing a lot of rewrites, hopefully all that will be fixed when I'm done.
Try the current code from here, I believe Konstantin is publishing it now as 1.4.2. 
I made some small improvements to the scrubbing, not sure if it's in that change, at least it should render a bit faster.

**Comment by morevnaproject** [comment]
Thank you for clarification @steveway! 

@Hippyjake, the 1.4.2 is here - https://morevnaproject.org/2017/07/31/papagayo-ng-1-4-2-released/

**Comment by Hippyjake** [comment]
The new version is faster but I still have the same visual glitches, tho the audio seems smoother. Thanks guys.
For now I'm using the old windows version (1.2) from the original author installed with wine :cry: lol

**Comment by steveway** [comment]
All that should currently be fixed for some time.
