### ISSUE TITLE
Double clicking the sentence doesn't show mouth movements

### ISSUE THREAD

**Issue by DarrenTAnims** [morevnaproject-org/papagayo-ng#31]
In the 1.4.2 version (could be the same in 1.4.1, I've not tried), clicking on a sentence plays the audio, but the mouth animations don't change. They used to on the original version, so I don't know if this is the move to NG. Clicking on individual words doesn't move the mouth either.

**Comment by steveway** [comment]
Seems to be fixed with: https://github.com/morevnaproject/papagayo-ng/pull/55
