### ISSUE TITLE
Suggestions for Phoneme/Word/Sentence dragging

### ISSUE THREAD

**Issue by steveway** [morevnaproject-org/papagayo-ng#34]
Hi, so I'm experimenting currently with rendering and interacting with our Phonemes, Words and Sentences in the WaveformView.
Currently I have it set so that you can resize the box by left-clicking inside the last few Pixels to the right of it and dragging the mouse.
If you left-click anywhere else inside such a widget then you can move it.
Both currently not restricted by the grid.
And a right-click in it an alternate function is executed. (Currently only a print to the console)
This does feel quite nice, we might change moving so the widget does not position it's left side at the mouse.
For testing it offers currently two independent widgets, test and test2.
What I would like to know is, how would you prefer these to interact on move and resize operations?
The way we have it in the current wx version feels slightly restricted and buggy.
This is one of the main interactions the user does with our program, so making this feel at least usable should be a goal.

**Comment by Hunanbean** [comment]
The ability to resize the word from either direction would be amazingly helpful and useful.
Fingers crossed
Thank you

**Comment by steveway** [comment]
@jensdreske Fixed resizing from both sides.
This is now fixed thanks to this: https://github.com/morevnaproject-org/papagayo-ng/pull/88

**Comment by Hunanbean** [comment]
That is very useful. Thank you
