### ISSUE TITLE
Papagayo on Arch Linux

### ISSUE THREAD

**Issue by jvault** [morevnaproject-org/papagayo-ng#35]
I had some problems during the execution both local installation and portable. 
Here some notes and how I solved them.

Dependencies (on site/appimage):
wxphython python-pyaudio libjpeg-turbo lidselinux(AUR)

**wxphython** is on
_/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_
need to bind it manually to
_/usr/lib/python3.6/site-packages/wx/_
or Install equivalent .from PIP ( *sorry I'm not sure which is the recommended).

Currently Arch Linux repos provides **libjpeg**=8.1.2 
need to install manually too
_/usr/lib/libjpeg.so.9.2.0
/usr/lib/libjpeg.so.9_

This is what I did to run in Antergos, may be some other discrepancies but this should be enough to run the app without problems.

**Comment by steveway** [comment]
This likely does not apply anymore since a lot changed with the code and we now create updated Appimages.
