### ISSUE TITLE
Integration with rhubarb-lip-sync?

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject-org/papagayo-ng#44]
Interesting project to consider - https://github.com/DanielSWolf/rhubarb-lip-sync

**Comment by morevnaproject** [comment]
https://github.com/morevnaproject/papagayo-ng/issues/51

**Comment by morevnaproject** [comment]
We've got Rhubarb feature merged just now. - #50 ^__^

**Comment by towfiqi** [comment]
Great! Can you kindly let me know how you are converting the shapes of phonemes to rhubarb shapes? I am trying to add a function to my project to convert the cmu-sphynx phonemes to rhubarb shapes. What I am trying is grouping each shapes to some phonemes. It works somewhat, but there are some descripencies:
```
    /*A*/ ["P", "B", "M"],
    /*B*/ ["K", "S", "T", "EE", "IY", "IH"],
    /*C*/ ["EH", "AE", "AH", "Schwa", "EY", "AY", "HH", "G", "CH", "JH", "R", "Y"],
    /*D*/ ["AA"],
    /*E*/ ["AO", "ER", "SH", "ZH"],
    /*F*/ ["UW", "OW", "W", "UH", "AW", "OY"],
    /*G*/ ["F", "V"],
    /*H*/ ["L", "N", "NG", "T", "D", "TH", "DH", "S", "Z", "D"],

```

It would be great if you could let me know what logic you are using to converting the phonemes to rhubarb shapes. I tried looking into the code, but I dont python, so couldn't figure it out. :disappointed: 

Thanks

**Comment by luzpaz** [comment]
nice
