### ISSUE TITLE
Appimage: Dragging elements in waveform view do not snap to frames

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject-org/papagayo-ng#46]
Dragging elements (phonemes, words, phrases)  in waveform view do not snap to frames. Their boundaries stay somewhere in between of frames.
As result, later Papagayo fails to export into .dat file with error:
```
Traceback (most recent call last):
  File "/tmp/.mount_1A9bvo/usr/opt/papagayong/LipsyncFrame.py", line 662, in OnVoiceExport
    self.doc.currentVoice.Export(dlg.GetPaths()[0])
  File "/tmp/.mount_1A9bvo/usr/opt/papagayong/LipsyncDoc.py", line 363, in Export
    for frame in range(startFrame, endFrame + 1):
TypeError: 'float' object cannot be interpreted as an integer
```

This happens on Appimage only. Appimage uses wxPhoenix 4.0.0a2.

This doesn't happens  when running from source with native ptyhon-wxgtk3.0 package v3.0.2.0 (Ubuntu).

Screenshot (after drag) - notice elements are not aligned with frame marks:
![screenshot_002](https://user-images.githubusercontent.com/332868/43504060-1633c288-958c-11e8-8865-f54bc802c84d.png)

**Comment by morevnaproject** [comment]
Possibly related with #45

**Comment by steveway** [comment]
I believe the dragging problems should be fixed with my pullrequest: https://github.com/morevnaproject/papagayo-ng/pull/55

**Comment by morevnaproject** [comment]
I need to build new appimage and test that. Depends on https://github.com/morevnaproject/papagayo-ng/issues/43. Thanks!

**Comment by steveway** [comment]
We got some new Appimages, as far as I know this bug does not apply anymore.
