### ISSUE TITLE
Save "mood" with sentences/words/phonemes.

### ISSUE THREAD

**Issue by steveway** [morevnaproject-org/papagayo-ng#5]
It would be quite interesting to save the "mood", like angry, happy, excited or so, to the phonemes.
We could then use that information in the export to choose some more mouths if they exist.
The older export formats can simply ignore this extra information.
Maybe we can add a textbox to enter the mood on the existing right-click menu.
##

**Comment by steveway** [comment]
I have thought about this a bit and instead of restricting this to "moods" it makes more sense to call it tags. We'll let the user type in a comma or space seperated list of tags and on export we walk through that list in order and use the corresponding mouth if it exists.
So the user types in for example something like this as tags for a part of his text: "left, angry"
And on export we'll then use the appropiate file in the subfolder left and it's subfolder angry of the currently selected mouth.
If the if the file does not exist we'll go back one step in the list and try again until we are at the main folder.

**Comment by MaskedRetriever** [comment]
Tags would also be a natural place to store information about the speaker.  For example, the mouths are selectable at the application level and selections don't attach to the different voices.  (I discovered this while implementing Chorus Mode because mouths didn't change between voices, and kind of can't.)

**Comment by steveway** [comment]
Tags are now integrated and will be saved if you use the new json based .pg2 project files.
Now we need some support for that in different animation software.
