### ISSUE TITLE
Rhubarb: Display GUI progressbar when parsing wave file

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject-org/papagayo-ng#51]
We need to show GUI progressbar while Rhubarb parses file.

**Comment by morevnaproject** [comment]
@evgenijkatunov ^__^

**Comment by steveway** [comment]
If we can get some progress information from Rhubarb then we can use the QProgressDialog to show it.
It's pretty easy to use, you'll find a few occurrences in my WaveformViewRewrite.py file.
And it has a minimun duration (can be changed) of time for which it shows, which is really nifty.
After studying rhubarb for a bit and our implementation, this seems easy to do:
Directly after line 55 in Rhubarb.py still in the else part we can get the current progress information with something like this:
```
if log_formatted['type'] == "progress":
    current_progress_in_percent = log_formatted['value'] * 100
```
We can use that value to show the current Progress then.

**Comment by steveway** [comment]
Added this in: https://github.com/morevnaproject-org/papagayo-ng/pull/78/commits/b9ac0afb8b8567c1be920059cc7e340957a897a6
I also added some support so it will work on Windows too.

**Comment by morevnaproject** [comment]
Awesome! Thank you!
