### ISSUE TITLE
help, help problem in importing mp3 files 

### ISSUE THREAD

**Issue by willy-oss** [morevnaproject-org/papagayo-ng#60]
hi everyone,
nice to meet you all. my issue is the strangest one ever because it occurs at my very first action on the software
so, when i click on open file to load an mp3 file into papagayo, nothing happens and the software stats idle. i use the app image of papagayo ng from morevna project since i do run ubuntu 18.04 as my main os. please what can i do .
Your help will really be useful
THANKS.

**Comment by dyter07** [comment]
Same issue here, cant open any mp3 file. Running Windows 10.

**Comment by dyter07** [comment]
Well, I just solved it myself. The problem is the RIFF ID. Just upload the mp3 to any online converter and convert it to wav, problem solved. :)

**Comment by steveway** [comment]
Hello this should work with my fork.
If you have a current version of Ubuntu, this error might exists on other distributions as well, then the included Portaudio is buggy.
Following the steps from this Stackoverflow answer worked for me:
https://stackoverflow.com/questions/59006083/how-to-install-portaudio-on-pi-properly
