### ISSUE TITLE
Not running correctly Win10 x86_64 #40

### ISSUE THREAD

**Issue by vladiR56** [morevnaproject-org/papagayo-ng#64]
Hallo, I have the same problem as Bang Droid. I'm getting unusual UI display running papagayo-ng on my machine.
The file I downloaded (PapagayoNG-testing-2017.07.31-65704-win-32bit.exe) came from https://gumroad.com/l/papagayo-ng directed from https://morevnaproject.org/papagayo-ng.
![image](https://user-images.githubusercontent.com/66032079/83168991-a781b400-a112-11ea-8f44-bf9ff0a4f6a4.png).
And here the bat file output:
C:\Program Files (x86)\Papagayo-NG>C:

C:\Program Files (x86)\Papagayo-NG>cd "C:\Program Files (x86)\Papagayo-NG\"

C:\Program Files (x86)\Papagayo-NG>python.exe papagayo-ng\papagayo-ng.py
C:\Program Files (x86)\Papagayo-NG\papagayo-ng\rsrc\mouths
('C:\\Program Files (x86)\\Papagayo-NG\\papagayo-ng\\rsrc\\mouths\\1 - Mouth 1', ['AI.png', 'E.png', 'etc.png', 'FV.png', 'L.png', 'MBP.png', 'O.png', 'rest.png', 'U.png', 'WQ.png'])
('C:\\Program Files (x86)\\Papagayo-NG\\papagayo-ng\\rsrc\\mouths\\2 - Mouth 2', ['AI.jpg', 'E.jpg', 'etc.jpg', 'FV.jpg', 'L.jpg', 'MBP.jpg', 'O.jpg', 'rest.jpg', 'U.jpg', 'WQ.jpg'])
('C:\\Program Files (x86)\\Papagayo-NG\\papagayo-ng\\rsrc\\mouths\\3 - Gary C Martin', ['AI.jpg', 'E.jpg', 'etc.jpg', 'FV.jpg', 'L.jpg', 'MBP.jpg', 'O.jpg', 'rest.jpg', 'U.jpg', 'WQ.jpg'])
('C:\\Program Files (x86)\\Papagayo-NG\\papagayo-ng\\rsrc\\mouths\\4 - Preston Blair', ['AI.jpg', 'E.jpg', 'etc.jpg', 'FV.jpg', 'L.jpg', 'MBP.jpg', 'O.jpg', 'rest.jpg', 'U.jpg', 'WQ.jpg'])
('C:\\Program Files (x86)\\Papagayo-NG\\papagayo-ng\\rsrc\\mouths\\5 - Fleming and Dobbs', ['AA.jpg', 'EHSZ.jpg', 'FV.jpg', 'GK.jpg', 'IY.jpg', 'MBP.jpg', 'NLTDR.jpg', 'O.jpg', 'rest.jpg', 'SH.jpg', 'source.sif', 'TH.jpg'])
('C:\\Program Files (x86)\\Papagayo-NG\\papagayo-ng\\rsrc\\mouths\\6 - Azia Comics 1 (preston_blair)', ['AI.jpg', 'E.jpg', 'etc.jpg', 'FV.jpg', 'L.jpg', 'MBP.jpg', 'O.jpg', 'rest.jpg', 'U.jpg', 'WQ.jpg'])
('C:\\Program Files (x86)\\Papagayo-NG\\papagayo-ng\\rsrc\\mouths\\7 - Azia Comics 2 (preston_blair)', ['AI.jpg', 'E.jpg', 'etc.jpg', 'FV.jpg', 'L.jpg', 'MBP.jpg', 'O.jpg', 'rest.jpg', 'U.jpg', 'WQ.jpg'])
['1 - Mouth 1', '2 - Mouth 2', '3 - Gary C Martin', '4 - Preston Blair', '5 - Fleming and Dobbs', '6 - Azia Comics 1 (preston_blair)', '7 - Azia Comics 2 (preston_blair)']
import phonemes_preston_blair as phonemeset

The program remains in this status. I changed the screen resolution but didn't help. Do you have any idea what else I can do?

**Comment by morevnaproject** [comment]
Hi! Please try to resize window - it should restore layout.

**Comment by vladiR56** [comment]
Hi Konstantin,
Thank you for your prompt reply.
Unfortunately changing the screen settings did not help. I also installed the old papagayo version 2.0b1 which works.
I currently have the following Settings:
[cid:image002.jpg@01D635A0.E94FF820]



What else could I try?
Vladi


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Konstantin Dmitriev<mailto:notifications@github.com>
Gesendet: Donnerstag, 28. Mai 2020 19:22
An: morevnaproject-org/papagayo-ng<mailto:papagayo-ng@noreply.github.com>
Cc: vladiR56<mailto:vladi_ragala@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [morevnaproject-org/papagayo-ng] Not running correctly Win10 x86_64 #40 (#64)


Hi! Please try to resize window - it should restore layout.

**Comment by morevnaproject** [comment]
Sorry, I cannot see any image attached. Can you please login to GitHub and attach image to your comment? (responding using email not works with attachments)

**Comment by vladiR56** [comment]
Yes, off Course.

Vladi


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Konstantin Dmitriev<mailto:notifications@github.com>
Gesendet: Freitag, 29. Mai 2020 10:21
An: morevnaproject-org/papagayo-ng<mailto:papagayo-ng@noreply.github.com>
Cc: vladiR56<mailto:vladi_ragala@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [morevnaproject-org/papagayo-ng] Not running correctly Win10 x86_64 #40 (#64)


Sorry, I cannot see any image attached. Can you please login to GitHub and attach image to your comment? (responding using email not works with attachments)

**Comment by vladiR56** [comment]
Hi, 
![Settings](https://user-images.githubusercontent.com/66032079/83264009-c38f5f00-a1bf-11ea-928e-e84194e29f0c.jpg)
I changed the resolution and scaling, but it didn't work.
Vladi

**Comment by steveway** [comment]
Hello Vladi,
That is not exactly what Konstantin tried to get you to do.
Try to use the bottom right corner of the Papagayo-NG window to change the size of the window itself.
This should trigger a resize event which likely will fix the layout.

**Comment by vladiR56** [comment]
Hi Stefan,
great, it works. Thank you very much.
Vladi

**Comment by vladiR56** [comment]
Hello everyone.
I'm a big fan of Papagayo. So I was happy because I found the Lip-SyncImporterBlender3_v1.py for Blender 3.5. I downloaded it. After that I want to install it in preferencies. Then this message came up: Modules Installed () from 'D:\\Projects\\Blender\\BLENDER_Add_ON\\Papagayo-NGLipsyncImporterForBlender-main.zip' into 'C:\\Users\\Vladi\\AppData\\Roaming\\ Blender Foundation\\Blender\\3.5\\scripts\\addons'
Unfortunately

I can't find the Lipsync addon in Preferences to activate it. What I have done wrong? Can you please help me?
 Vladimir

**Comment by steveway** [comment]
I don't know how that Plugin for Blender is working.
It would be best to raise an Issue with the creator.
I assume that you mean this project?: https://github.com/Hunanbean/Papagayo-NGLipsyncImporterForBlender
