### ISSUE TITLE
Unable to process common words, is an external dictionary required?

### ISSUE THREAD

**Issue by Hunanbean** [morevnaproject-org/papagayo-ng#67]
During breakdown, i am required to manually breakdown Way to may words., example the word 'Once' also, it does not ignore quotes ""
I would imagine there is an external dictionary i am supposed to load, or the contained ones are not working properly. I have pressed reload dictionary.
please advise. for reference, i do not have these problems with the original papagayo.

also the U.I. problem mentioned in Issue #19 is still present

Be well

**Comment by steveway** [comment]
I added the ' symbol to the strip marks in Pull Request #69 
With this it should also break down the word 'Once' with those single quotation marks.

**Comment by Hunanbean** [comment]
Thank you for the quick response and action. i look forward to testing it once merged.
However, i only included the ' ' around the word Once for clarification, it is actually having trouble with the word Once

Thank you and be well

**Comment by Hunanbean** [comment]
Ok, i think i understand now how to append instead of waiting for merge. I will test it now.
Thanks again!
