### ISSUE TITLE
Cannot drag a .wav file to interface

### ISSUE THREAD

**Issue by Hunanbean** [morevnaproject-org/papagayo-ng#68]
unable to drag and drop an audio file to the interface. i must use the menu/icon options to open an audio file. I do not know if this is by design, or an oversight.

**Comment by steveway** [comment]
It took a bit of experimenting but I think I got this added now.
The update is available in Pull Request #69

**Comment by Hunanbean** [comment]
Thank you again for the quick response and action!
I will test this when merged.

Be well

**Comment by Hunanbean** [comment]
I downloaded the new source code and installed the requirements, but when trying to run it, i get the following error message

`Designer: An error has occurred while reading the UI file at line 1, column 0: Premature end of document.
Traceback (most recent call last):
  File ".\papagayo-ngn\papagayo-ng.py", line 9, in <module>
    papagayo_window = LipsyncFrameQT.LipsyncFrame()
  File "O:\papagayo-ng-master\papagayo-ngn\LipsyncFrameQT.py", line 90, in __init__
    self.main_window = self.load_ui_widget(self.ui_path)
  File "O:\papagayo-ng-master\papagayo-ngn\LipsyncFrameQT.py", line 229, in load_ui_widget
    self.ui = self.loader.load(file, parent)
RuntimeError: Unable to open/read ui device`

Hopefully it is just something i did incorrectly. 
Thank you and be well

**Comment by Hunanbean** [comment]
The previous error message only appeared when i downloaded a .zip of the code instead of cloning.
when running from clone, the error does not appear. unfortunately, the drag to drop .wav is also not functioning. the version report under about is still 1.4.2
due to the fact that cloning the code base changed all file dates to the moment i downloaded them, i cannot easily verify that they are the new files. I am going to dig a bit deeper and check to see if some of the changes you made are present.

**Comment by Hunanbean** [comment]
Ok, i have verified that the recent changes are what i have localized from the clone, so the error message is gone and the dratg and drop is working now!

Thank you again
