### ISSUE TITLE
Multiple errors in CMU pronunciation dictionary, any known alternatives?

### ISSUE THREAD

**Issue by Hunanbean** [morevnaproject-org/papagayo-ng#76]
There are countless errors in the CMU pronunciation dictionary, to the point where it cannot be relied upon. Does anyone know of a 'plug and play' alternative dictionary?

i noticed this while working with it, and verified from other sources. it is simply errant.

**Comment by Hunanbean** [comment]
Turns out the dictionary base that is being used is the CMU version from 1998 or so. Locally i have updated to the latest 2015 CMU version 0.7b, and notice substantially less pronunciation errors. after further testing, i will attempt a Merge request. i am new to Github, so hoping for the best.

**Comment by steveway** [comment]
I see, that sounds like a good idea.
It seems that the file format changed slightly, so the loading needs to be adjusted.
That part has not been touched since the beginning practically.

**Comment by Hunanbean** [comment]
Yes, i went ahead and changed the formatting to match the 1998 version and all is working well unless i missed something that has not given me an issue yet. i just replaced ;;; with ##

**Comment by steveway** [comment]
Mhh, I think I prefer adjusting our code so that we can load the files without changing them.
That should not be too difficult, the format seems to be mostly the same as before.

**Comment by Hunanbean** [comment]
Makes sense. The one that i had modified is this one, which is the official version [https://github.com/Alexir/CMUdict/blob/master/cmudict-0.7b](url)
I only mention this, because there is another version floating around that has been modified further with the addition of more control characters in unusual places and a large amount of middle eastern names. it is easily distinguishable by the addition of a 2018-2020 copyright claim by an additional third party. 
This is "just in case" information that probably does not apply.
Since you are going that direction with it, i will not attempt a merge request for the altered dictionary, and instead just wait for your update.

**Comment by steveway** [comment]
I updated it to use the newest version 0.7b from here:
http://www.speech.cs.cmu.edu/cgi-bin/cmudict
That seems to be the most official source I believe, but I'm not sure exactly.

**Comment by Hunanbean** [comment]
Cool deal, that looks perfect.

Thank you
