### ISSUE TITLE
Finicky execution

### ISSUE THREAD

**Issue by Hunanbean** [morevnaproject-org/papagayo-ng#77]
papagayo-ng using the current code base 08/14/2020 with all 'requirements.txt' met to the best of my knowledge.
The program only fully loads about 50% of the times i try to open it. i get no error messages. the GUI never appears when it fails.
there is no rhyme or reason as to why it chooses to work, or not. i have run a full windows 10 defender scan with 0 threats found.
I cannot verify if this is a problem with my computer, something i am doing incorrectly, or if there is something in the code base causing this.
if i ever get an actual error message i will update this.
no change if i run as elevated. 
also, when does it fail, there are no running instances python.exe in task manager. also using 3rd party tools, i see no references to python running when it does not display the GUI.
I have no insight as to why or what is going on. i can say, while typing this message, i was able to open it twice with no issues, then 4 fails in a row, then one more success. I am baffled.
running windows updates, and updating video card drivers now. (i probably should have done that before opening this issue)

Thank you, and sorry to be the bearer of bad news

**Comment by Hunanbean** [comment]
Perhaps it has to do with slightly different version of the requirements.

`Requirement already satisfied: sounddevice>=0.3.13 in o:\mymodpapagayo\lib\site-packages (from -r requirements.txt (line 1)) (0.4.0)
Requirement already satisfied: cffi>=1.12.2 in o:\mymodpapagayo\lib\site-packages (from -r requirements.txt (line 2)) (1.14.1)
Requirement already satisfied: numpy>=1.16.2 in o:\mymodpapagayo\lib\site-packages (from -r requirements.txt (line 3)) (1.19.1)
Requirement already satisfied: pydub>=0.23.1 in o:\mymodpapagayo\lib\site-packages (from -r requirements.txt (line 4)) (0.24.1)
Requirement already satisfied: anytree>=2.6.0 in o:\mymodpapagayo\lib\site-packages (from -r requirements.txt (line 5)) (2.8.0)
Requirement already satisfied: PySide2>=5.12.3 in o:\mymodpapagayo\lib\site-packages (from -r requirements.txt (line 6)) (5.15.0)
Requirement already satisfied: pycparser in o:\mymodpapagayo\lib\site-packages (from cffi>=1.12.2->-r requirements.txt (line 2)) (2.20)
Requirement already satisfied: six>=1.9.0 in o:\mymodpapagayo\lib\site-packages (from anytree>=2.6.0->-r requirements.txt (line 5)) (1.15.0)
Requirement already satisfied: shiboken2==5.15.0 in o:\mymodpapagayo\lib\site-packages (from PySide2>=5.12.3->-r requirements.txt (line 6)) (5.15.0)`

Any ideas/suggestions are welcome, thanks

**Comment by steveway** [comment]
Yeah, I had that too.
It's very difficult to analyze because QT crashes without any real information.
But after some experiments I think I found a possible fix, see this comment for further details:
https://github.com/morevnaproject-org/papagayo-ng/issues/74#issuecomment-674857785
I'll have to do some tests to see if everything works without that one line.

**Comment by Hunanbean** [comment]
Sounds good. Hopefully that will do it.
