### ISSUE TITLE
Program semi locks and loses functionality after attempting to load a moved project

### ISSUE THREAD

**Issue by Hunanbean** [morevnaproject-org/papagayo-ng#79]
if you attempt to load a project that you have previously manually moved the directory/folder location of, the program slows and loses most functionality. 
Example:
working on a project, decide to switch over to a different project. go to file>load. i select a file that i had moved to a sub directory earlier. the program hangs on trying to find audio. i cancel this load, it drops me back into the project i was working on before i attempted loading the moved project, but i cannot work with the project. some functionality is simply missing, or does not respond to clicks or actions. only solution i have found is a close and restart of the program.

**Comment by steveway** [comment]
I think I know what you mean.
I did some changes which check if the sound file exists at the path and if not it should say so and open a file dialog to choose the audio file:
https://github.com/steveway/papagayo-ng/commit/3e85c862d7269e15711d331e381c2a7c4688192b

**Comment by Hunanbean** [comment]
Ok, thank you very much! I will check those changes as soon as it is merged. It is just easier for me to wait and make a full copy of the code instead of piecing things together and screwing something up on my end
