### ISSUE TITLE
Support for more than .wav files

### ISSUE THREAD

**Issue by steveway** [morevnaproject-org/papagayo-ng#8]
If I haven't missed anything then papagayo only supports .wav files at the moment.
We might use something like this to convert other audio files on the fly:
http://pymedia.org/tut/src/dump_wav.py.html
Or, I would prefer pydub, maybe scrap using the wave library directly and instead use pydub:
http://pydub.com/
BTW.: Hope I don't annoy with these "Issues", I'm trying to organize this a bit and mark some hopefully interesting workloads so we can make this thing great.
##

**Comment by steveway** [comment]
My latest commit to testing has a first working version of using pydub for this.
Tested on Windows.
https://github.com/steveway/papagayo/commit/0feebd2e0adc04d007ab01cd7ada0cf01c537c6b

**Comment by morevnaproject** [comment]
I have merged your changes. Added a few tweaks:
* Allow to run Papagayo if PyDub not available
* Added searching for ffmpeg in PATH
* Also search for "avconv", as alternative to ffmpeg
* Support to call ffmepg on Linux/OSX (not tested)

**Comment by steveway** [comment]
Nice, I'll try the current state out and push this back to my fork later.
I've got some more things I wan't to try to add.

**Comment by steveway** [comment]
Should be fixed.
It's best to have FFmpeg downloaded, which can be done from inside Papagayo-NG.
