### ISSUE TITLE
Adding additional faces does not stay in logical numeric order

### ISSUE THREAD

**Issue by Hunanbean** [morevnaproject-org/papagayo-ng#80]
I have made a custom phoneme set for the 39 base CMU phonemes. I have created two new 'Mouths' to match this extended set that i have added as number 9 and number 10 in my local install. when i go to select the mouths, instead of being ordered, 1, 2, 3.. they are ordered 1, 10, 2, 3..

I am about to attempt a merge request, but am waiting for word on how this should be handled.

Thank you

**Comment by steveway** [comment]
I see, this should be improved in https://github.com/steveway/papagayo-ng/commit/b7256a94f84b47f544a668c9b29f861fd3479eea
I am trying to sort the Mouths based on the first part of the name converted to an Integer.
In case that this part can't be converted there is also a fallback using hash().

**Comment by Hunanbean** [comment]
Thank you once again.
Should i try an actual merge request, or perhaps just upload my changes to googledrive, or some source, for you to see and decide integration that way? 
Although i have everything working in my local Blender setup, i am still working on actual integrated, shareable visemes for use in MakeHuman. I am posting a demonstration of a lipsync with the full viseme set, and will make a comment here when it is uploaded.

**Comment by steveway** [comment]
I merged my changes just now.
If you do a Pull Request I will take a look at it as soon as I find some time.
Depending on how it fits we'll merge it directly or do some changes beforehand.

**Comment by Hunanbean** [comment]
Here is a quick 8 second video demonstration of the 39 viseme set in action. best to watch at .75 speed.
 [https://youtu.be/FXMNr-oWJ4U](url)

**Comment by Hunanbean** [comment]
I am holding off on a pull request until I have the visemes in MakeHuman Target sharable format. right now, they are only shapekeys in blender that require a procedure to be followed, instead of usable by all models/configurations in MakeHuman. Should only be a couple days until i am done with that. i will check your fix as soon as possible. Thank you

**Comment by Hunanbean** [comment]
Ok, that took longer than i had hoped. I do not want to disturb your repo with a pull request and all that jazz, so here is a link to the github page containing just the additions of mouths and a phoneme list. 
I do hope you will merge this, as i am creating a series of tutorials and resources for others to use.
I have succesfully created the MakeHuman shareable visemes which will also be posted to the hunanbean.collective github page.
[https://github.com/Hunanbean-Collective/Papagayo-NG-Additions](url)
Thank you, and be well
