### ISSUE TITLE
Remove w9xpopen from installation

### ISSUE THREAD

**Issue by ice0** [morevnaproject-org/papagayo-ng#84]
https://stackoverflow.com/questions/1904724/py2exe-are-manifest-files-and-w9xpopen-exe-required-when-compiling-a-web-server

```
w9xpopen.exe is for windows 95/98, So If you don't use those you will not need it.
```

**Comment by steveway** [comment]
I believe since we are currently using PyInstaller to bundle the Windows version this is not applicable anymore.
