### ISSUE TITLE
Papagayo won't display wavelength when I put in my WAV files.

### ISSUE THREAD

**Issue by IamaGitUser1** [morevnaproject-org/papagayo-ng#87]
![Image](https://user-images.githubusercontent.com/82460255/114574126-e2300480-9c70-11eb-9a41-f82da3a0ae71.png)

**Comment by steveway** [comment]
Hello,
You are trying to use a different project.
This here is for Papagayo-NG, which is a more modern fork.
You can get it either from the source code in this repository.
From this page:
https://morevnaproject.org/papagayo-ng/
Or from my Patreon:
https://www.patreon.com/steveway
