### ISSUE TITLE
Requesting Settings be moved to Edit menu

### ISSUE THREAD

**Issue by Hunanbean** [morevnaproject-org/papagayo-ng#95]
In order to be in line with other software, including Blender (they finally moved it) perhaps the Settings could be moved to the Edit menu, and possibly changed to Preferences?

Thank you

**Comment by steveway** [comment]
Ok, I changed this in my current code.
There is no new installer yet, but this change will be in the next update.
I also updated the icons and added new ones.
![new_settings](https://user-images.githubusercontent.com/3737094/125074956-47ec2b00-e0be-11eb-93d8-a150e3c38baf.png)

**Comment by Hunanbean** [comment]
That looks great! Thank you
